name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Gradle Build
      run: ./gradlew build

    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  hurzelpurzel/micro-jobs-server:latest 