name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  hurzelpurzel/micro-jobs-server:latest 